config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
    end
  get 'admin/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  resources :orders
  resources :line_items
  resources :carts
  get 'store/index'
  resources :products do
  	get :who_bought, on: :member
  end
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'store#index', as: 'store'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Card Shop</title>
	<%= stylesheet_link_tag "application", media: "all",
	"data-turbolinks-track" => true %>
	<%= javascript_include_tag "application",
	"data-turbolinks-track" => true %>
	<%= csrf_meta_tag %>
</head>
<body class="<%= controller.controller_name %>">
	<div id="banner">
		<%= image_tag("logo.png") %>
		<%= @page_title || "Магазин синловой продукции" %>
	</div>
	<div id="columns">
		<div id="side">
			<% if @cart %>
			<%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
			<%= render @cart %>
			<% end %>
			<% end %>
			<ul>
				<li><a href="http://localhost:3000/">Домой</a></li>
				<li><a href="http://www..../faq">Вопросы</a></li>
				<li><a href="http://www..../news">Новости</a></li>
				<li><a href="http://www..../contact">Контакты</a></li>
			</ul>
			<% if session[:user_id] %>
			<ul>
			<li><%= link_to 'Заказы', orders_path %></li>
			<li><%= link_to 'Товары', products_path %></li>
			<li><%= link_to 'Пользователи', users_path %></li>
		</ul>
		<%= button_to 'Выйти', logout_path, method: :delete %>
		<% end %>
	</div>
	<div id="main">
		<%= yield %>
	</div>
</div>
</body>
</html>